Attach rocket boosters to deploy script

diff --git a/scripts/deploy b/scripts/deploy
--- a/scripts/deploy
+++ b/scripts/deploy
@@ -2,36 +2,37 @@
 
 SCRIPTDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
 ROOTDIR=$(cd $SCRIPTDIR && cd ../ && pwd || exit)
-SECRET=$( [ -f $ROOTDIR/data/ftp_pass ] && cat $ROOTDIR/data/ftp_pass || [ ! -z $FTP_PASS ] && echo $FTP_PASS || false)
+# SECRET=$( [ -f $ROOTDIR/data/ftp_pass ] && cat $ROOTDIR/data/ftp_pass || [ ! -z $FTP_PASS ] && echo $FTP_PASS || false)
 
 # Pretty colors
-GREEN='\033[0;32m'
 ORANGE='\033[0;33m'
-CYAN='\033[0;36m'
 BOLD='\E[1m'
 NC='\033[0m'
 
 # Check to see that we have access to the FTP password
-if [ ! $SECRET ]; then echo "SECRET could not be set!"; exit 1; fi
+# if [ ! $SECRET ]; then echo "SECRET could not be set!"; exit 1; fi
 
-cd $ROOTDIR || exit 1
+# cd $ROOTDIR || exit 1
 
 # Compile the code
 $ROOTDIR/node_modules/.bin/gulp build
 
-cd $ROOTDIR/dist || exit 1
+type rsync &>/dev/null
+if [[ $? == 1 ]]; then
+    echo '=> Error: rsync must be installed.'
+    exit 1
+fi
 
-# Create an array containing all filenames within Divi-child
-divi_child=()
-while read file; do
-    divi_child+=($file)
-done <<< "$(find Divi-child -type f)"
+# Exit if the DSA file doesn't exist
+if [[ ! -f ./data/aliemu_dsa ]]; then
+    echo '=> Error: You must have the file "aliemu_dsa" located within your data directory'
+    exit 1
+fi
 
-# Transfer Divi-child files to server with FTP
+chmod 400 $ROOTDIR/data/aliemu_dsa
+eval "$(ssh-agent -s)" &>/dev/null
+ssh-add $ROOTDIR/data/aliemu_dsa &>/dev/null
+
 echo -e "${ORANGE}${BOLD}==> Deploying...${NC}"
-for i in "${!divi_child[@]}"; do
-    printf "${CYAN}${BOLD}  ->${NC} ${GREEN}(%02d/${#divi_child[@]})${NC} ${divi_child[$i]}\n" $(($i+1))
-    curl -sS -u dsifford@aliemu.com:$SECRET --ftp-create-dirs -T ${divi_child[$i]} ftp://ftp.aliemu.com/wp-content/themes/${divi_child[$i]}
-done
-
+rsync --progress -az -e "ssh -i $ROOTDIR/data/aliemu_dsa -p 18765" "$ROOTDIR/dist/Divi-child/" aliemu@c7563.sgvps.net:public_html/wp-content/themes/Divi-child
 echo -e "${ORANGE}${BOLD}==> Deploy Finished.${NC}"
