Small tweaks (#30)
* Clean up colors.styl

* Fix a few buggy areas of server deploy script

* Various tweaks...

- Move coverage dir to new 'tmp' dir and adjust travis accordingly.
- Adjust 'staging' compose file for emintro domain.
- Heavily refactor gulpfile for readability.
- Add SITE_NAME variable to .env file so it can be used in various
  locations within the docker-compose files.
- Fix up deploy script.
- Add prompt in server-deploy script for SITE_NAME.
- Switch server-deploy script to digitalocean nyc1 region so we can use
  block storage.
- Add nodejs and npm in server so we can run one-off commands to fix
  dependencies.
- Add csso to devDependencies for minifying dependency files.
- Add merge-stream to devDependencies so gulpfile could be condensed and
  more readable.
- Add 'minify' script which should **only be ran on the server**.

* Various improvements...

- Add SVG for both footer logos.
- Fix typo in gulpfile.
- Adjust server-deploy script.

* Adjust scripts

* Update server-deploy script

* Various changes...

- Add back the email function for dashboard access until the slackbot
  becomes more reliable.
- Remove staging compose file.
- Add 'machine_name' to .env to enable polymorphism of the server
  scripts.
- Make some of the .env variables lowercase to prevent shadowing system
  environment variables.
- Version bump dependencies.
- Various small tweaks to some of the scripts.

* Add some new TypeScript 2.0 options to tsconfig.json

* Fix caps issue in compose base file

* Various fixes...

- Remove unused params and variables from TS files.
- Fix port mapping on compose files.
- Rename child theme 'aliemu', rather than 'Divi-child' -- Never knew
  you could do that!
- Adjust all files accordingly after the previous rename.

* Improve stylus gulp tasks

* Various changes to server-deploy

- Switch to ubuntu xenial on digitalocean
- Fix broken docker-compose install line
- Separate nodejs install line
- Automatically associate domain names with server
- Automatically start docker-compose build on build success

* Update package deps

* Update dependencies

* Fix type errors

* Fix failed test

* Fix line-breaking issue on macs

* Adjust team credentials

* update deps

diff --git a/lib/scripts/server-deploy b/lib/scripts/server-deploy
--- a/lib/scripts/server-deploy
+++ b/lib/scripts/server-deploy
@@ -1,7 +1,7 @@
-#!/bin/bash
+#!/usr/bin/env bash
 
 SCRIPTDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
-ROOTDIR=$(cd $SCRIPTDIR && cd ../../ && pwd || exit)
+ROOTDIR="$(cd $SCRIPTDIR && cd ../../ && pwd || exit)"
 
 # shellcheck source=./helpers
 source "$SCRIPTDIR/helpers" || exit 1
@@ -10,8 +10,10 @@ main() {
 
     # shellcheck source=../.env
     source $ROOTDIR/.env
-    [[ ! $SSHPASS ]] && ERROR "Couldn't find 'SSHPASS' variable in .env file"
-    [[ ! $TOKEN ]] && ERROR "Couldn't find 'TOKEN' variable in .env file"
+    ssh_pass=${ssh_pass:-}
+    token=${token:-}
+    [[ ! $ssh_pass ]] && ERROR "Couldn't find 'ssh_pass' variable in .env file"
+    [[ ! $token ]] && ERROR "Couldn't find 'token' variable in .env file"
 
     local droplets droplet
 
@@ -29,13 +31,30 @@ main() {
         sshpass
 
     h2 'Gathering needed information...'
-    read -p "$(h3 "Enter machine name:")" machine_name
-    read -p "$(h3 "Enter SSH/sudo password:")" -s sudo_pass && echo ""
+    read -p "$(h3 'Enter machine name:')" machine_name
+    read -p "$(h3 'Enter site name + TLD:')" -e site_name
+    while [ true ]; do
+        read -p "$(h3 "Enter SSH/sudo password:")" -s sudo_pass && echo ""
+        read -p "$(h3 "Reenter SSH/sudo password:")" -s sudo_pass_confirm && echo ""
+        [[ $sudo_pass == "$sudo_pass_confirm" ]] && unset -v sudo_pass_confirm && break
+    done
 
+    h3 'Setting machine_name in local .env file'
+    grep -q '^machine_name=' $ROOTDIR/.env && sed -i "s/^machine_name=.*/machine_name=$machine_name/" "$ROOTDIR/.env" \
+        || sed -i "$ a\machine_name=$machine_name" "$ROOTDIR/.env"
+    STATUS fatal 'Could not set machine_name in local .env file. Does the file exist?'
+
+    h3 'Setting site_name in local .env file'
+    grep -q '^site_name=' $ROOTDIR/.env && sed -i "s/^site_name=.*/site_name=$site_name/" "$ROOTDIR/.env" \
+        || sed -i "$ a\site_name=$site_name" "$ROOTDIR/.env"
+    STATUS fatal 'Could not set site_name in local .env file. Does the file exist?'
+
+
+    h3 "Connecting to DigitalOcean"
     droplets=$(
         curl -s \
             -X GET \
-            -H "Authorization: Bearer $TOKEN" \
+            -H "Authorization: Bearer $token" \
             "https://api.digitalocean.com/v2/droplets" \
         | jq -r '.droplets | map_values(.name) | join(" ")' 2>/dev/null
     )
@@ -67,36 +86,49 @@ main() {
 init() {
 
     local docker_compose_version
-
-    docker_compose_version=$(git ls-remote https://github.com/docker/compose | tail -n8 | awk '{print $2}' | grep -Po 'refs/tags/\K([\d.]{5})(?!-\w+)' | tail -n1)
+    docker_compose_version=$(curl -s -X GET "https://api.github.com/repos/docker/compose/releases/latest" | jq -r '.tag_name')
 
     h2 'Provisioning Docker Machine...'
     docker-machine create \
         -d digitalocean \
-        --digitalocean-access-token=$TOKEN \
+        --digitalocean-image=ubuntu-16-04-x64 \
+        --digitalocean-access-token=$token \
+        --digitalocean-region=nyc1 \
         $machine_name
 
     h2 'Setting up machine...'
 
-    h3 "Attaching to machine '$machine_name'"
-    eval "$(docker-machine env $machine_name)"
+    h2 'Updating kernel & installing dependencies'
+    docker-machine ssh $machine_name "
+    apt-get update \
+    && apt-get upgrade -y \
+    && DEBIAN_FRONTEND=noninteractive apt-get install -y \
+        build-essential \
+        vim
+    "
+
+    h3 'Installing Docker Compose'
+    docker-machine ssh $machine_name "curl -sL https://github.com/docker/compose/releases/download/$docker_compose_version/docker-compose-Linux-x86_64 > /usr/local/bin/docker-compose \
+    && chmod +x /usr/local/bin/docker-compose
+    "
     STATUS
 
-    h2 'Updating kernel & installing dependencies on host machine'
+    h3 'Installing NodeJS'
     docker-machine ssh $machine_name "
-    apt-get update && \
-    apt-get upgrade -y && \
-    DEBIAN_FRONTEND=noninteractive apt-get install -y vim &&
-    curl -L https://github.com/docker/compose/releases/download/$docker_compose_version/docker-compose-Linux-x86_64 > /usr/local/bin/docker-compose && \
-    chmod +x /usr/local/bin/docker-compose
+    curl -sL https://deb.nodesource.com/setup_6.x -o nodesource_setup.sh \
+    && chmod +x nodesource_setup.sh \
+    && ./nodesource_setup.sh &>/dev/null \
+    && DEBIAN_FRONTEND=noninteractive && apt-get install -y nodejs &>/dev/null \
+    && npm i -g uglify-js csso &>/dev/null
     "
+    STATUS
 
     h3 'Initializing filesystem & setting root access password'
     docker-machine ssh $machine_name "
     mkdir -p /app
     chown -R :www-data /app
     chmod -R g+rwx /app
-    echo 'root:$SSHPASS' | chpasswd
+    echo 'root:$ssh_pass' | chpasswd
     "
     STATUS
 
@@ -130,12 +162,25 @@ init() {
       ssh-keyscan -H "$(docker-machine ip $machine_name)" >> ~/.ssh/known_hosts
     fi
 
-    rsync --info=progress2 -az -e "ssh -i ~/.ssh/DO_${machine_name}_rsa" "$ROOTDIR/dist" "$(docker-machine ip $machine_name)":/app
-    rsync --info=progress2 -az -e "ssh -i ~/.ssh/DO_${machine_name}_rsa" "$ROOTDIR/wp-content" "$(docker-machine ip $machine_name)":/app
-    rsync --info=progress2 -az -e "ssh -i ~/.ssh/DO_${machine_name}_rsa" "$ROOTDIR/data" "$(docker-machine ip $machine_name)":/app
-    rsync --info=progress2 -aOz --chown=$USER:www-data --no-p -e "ssh -i ~/.ssh/DO_${machine_name}_rsa" --include="docker-compose*" --include=".env" --exclude="*" "$ROOTDIR/" "$(docker-machine ip $machine_name):/app"
+    rsync --info=progress2 -aOz --chown=$USER:www-data --no-p -e "ssh -i ~/.ssh/DO_${machine_name}_rsa" \
+        --include="docker-compose*" \
+        --include=".env" \
+        --include="dist/***" \
+        --include="wp-content/***" \
+        --include="data/***" \
+        --include="lib" \
+        --include="lib/compose.yml" \
+        --include="lib/scripts" \
+        --include="lib/scripts/minify" \
+        --exclude="*" \
+    "$ROOTDIR/" "$(docker-machine ip $machine_name):/app"
+
+    h3 'Creating package.json'
+    docker-machine ssh $machine_name "echo '{\"scripts\": {\"minify\": \"./lib/scripts/minify\"}}' > /app/package.json"
+    STATUS
 
     h2 'Finalizing transfer'
+
     h3 'Adjusting file ownership of /app directory'
     docker-machine ssh $machine_name "
     chown -R www-data:www-data /app
@@ -143,7 +188,31 @@ init() {
     "
     STATUS
 
-    h2 "Server Deployment Finished"
+    h2 "Associating domain name '$site_name' with droplet"
+
+    existing_domain=$(curl -s \
+    -X GET \
+    -H "Authorization: Bearer $token" \
+    "https://api.digitalocean.com/v2/domains/$site_name" \
+    | jq -r '.domain')
+
+    if [[ $existing_domain != 'null' ]]; then
+        # domain exists
+        update_domain_records "$(docker-machine ip $machine_name)"
+    else
+        # domain does not exist
+        create_domain_records "$(docker-machine ip $machine_name)"
+    fi
+
+    h2 'Server Deployment Finished. Rebooting...'
+    docker-machine restart $machine_name
+
+    h2 'Deploying site'
+    docker-machine ssh $machine_name "
+    cd /app
+    docker-compose -f docker-compose.prod.yml up -d
+    "
+
 }
 
 attach() {
@@ -155,8 +224,8 @@ attach() {
         curl -s \
             -X GET \
             -H "Content-Type: application/json" \
-            -H "Authorization: Bearer $TOKEN" \
-            "https://api.digitalocean.com/v2/droplets?page=1&per_page=1" \
+            -H "Authorization: Bearer $token" \
+            "https://api.digitalocean.com/v2/droplets" \
         | jq -r '.droplets | map(select(.name == "'$machine_name'")) | map(.networks.v4[].ip_address) | .[0]'
     )
     [[ $droplet_ip == 'null' ]] && ERROR "Could not determine droplet IP for $machine_name"
@@ -169,7 +238,7 @@ attach() {
     mkdir -p $HOME/.ssh
     rm -f "$HOME/.ssh/DO_${machine_name}_rsa" "$HOME/.ssh/DO_${machine_name}_rsa.pub"
     ssh-keygen -t rsa -N "" -f "$HOME/.ssh/DO_${machine_name}_rsa" &>/dev/null
-    cat "$HOME/.ssh/DO_${machine_name}_rsa.pub" | sshpass -p $SSHPASS ssh root@$droplet_ip "
+    cat "$HOME/.ssh/DO_${machine_name}_rsa.pub" | sshpass -p $ssh_pass ssh root@$droplet_ip "
     cat >> /root/.ssh/authorized_keys
     chmod 700 /root/.ssh
     chmod 600 /root/.ssh/authorized_keys
@@ -184,10 +253,6 @@ attach() {
         $machine_name
 
     h2 "Setting up machine for $USER..."
-
-    h3 "Attaching to machine '$machine_name'"
-    eval "$(docker-machine env $machine_name)"
-    STATUS
 
     h3 "Creating user '$USER' with sudo priveledges"
     docker-machine ssh $machine_name "
@@ -207,11 +272,59 @@ attach() {
     "
     STATUS
 
-    h2 'Restarting Docker Compose services'
-    docker-machine ssh $machine_name "cd /app && docker-compose restart"
+    # FIXME: Not sure why I added this in here to begin with
+    # h2 'Restarting Docker Compose services'
+    # docker-machine ssh $machine_name "cd /app && docker-compose restart"
 
     h2 "Server attachment finished"
 
+}
+
+update_domain_records() {
+    local droplet_ip=${1?'IP address must be passed into this function'}
+    local records
+
+    h3 "Domain found. Retrieving list of 'A' records from DigitalOcean"
+    records=$(curl -s \
+        -X GET \
+        -H "Authorization: Bearer $token" \
+        "https://api.digitalocean.com/v2/domains/$site_name/records" \
+        | jq -r '.domain_records | map(select(.type == "A")) | map_values(.id | tostring) | join(" ")'
+    )
+    STATUS
+
+    for id in $records; do
+        h3 "Updating IP for record id $id"
+        curl -s \
+            -X PUT \
+            -H "Content-Type: application/json" \
+            -H "Authorization: Bearer $token" \
+            -d "{\"data\":\"$droplet_ip\"}" "https://api.digitalocean.com/v2/domains/$site_name/records/$id" \
+            &>/dev/null
+        STATUS
+    done;
+}
+
+create_domain_records() {
+    local droplet_ip=${1?'IP address must be passed into this function'}
+
+    h3 'Existing domain record not found. Creating new record'
+    curl \
+        -X POST \
+        -H "Content-Type: application/json" \
+        -H "Authorization: Bearer $token" \
+        -d "{\"name\":\"$site_name\",\"ip_address\":\"$droplet_ip\"}" \
+        "https://api.digitalocean.com/v2/domains" &>/dev/null
+    STATUS
+
+    h3 "Creating 'A' record for www"
+    curl \
+        -X POST \
+        -H "Content-Type: application/json" \
+        -H "Authorization: Bearer $token" \
+        -d "{\"type\":\"A\",\"name\":\"www\",\"data\":\"$droplet_ip\",\"priority\":null,\"port\":null,\"weight\":null}" \
+        "https://api.digitalocean.com/v2/domains/$site_name/records" &>/dev/null
+    STATUS
 }
 
 main
